#ifndef CONFIGTOOL_RESOURCE_H
#define CONFIGTOOL_RESOURCE_H

// Dialog resource ID
#define IDD_CONFIG                      101
#define IDI_ICON                        102

// String Table IDs for English (1000-1999)
#define IDS_DIALOG_TITLE                1000
#define IDS_BTN_OK                      1001
#define IDS_BTN_CANCEL                  1002
#define IDS_BTN_DEFAULTS                1003
#define IDS_RESET_CONFIRM               1004
#define IDS_RESET_TITLE                 1005
#define IDS_GROUP_STARTUP               1006
#define IDS_GROUP_GRAPHICS              1007
#define IDS_GROUP_WINDOW                1008
#define IDS_GROUP_GAME                  1009
#define IDS_GROUP_INTERFACE             1010
#define IDS_LOG_MODE                    1011
#define IDS_LOG_APPEND                  1012
#define IDS_LOG_OVERWRITE               1013
#define IDS_VERBOSE                     1014
#define IDS_MANUAL_SETUP                1015
#define IDS_LOAD_ALL_MGR                1016
#define IDS_LOAD_ALL_BB                 1017
#define IDS_LOAD_ALL_PLUGINS            1018
#define IDS_DRIVER_ID                   1019
#define IDS_BPP                         1020
#define IDS_WIDTH                       1021
#define IDS_HEIGHT                      1022
#define IDS_FULLSCREEN                  1023
#define IDS_DISABLE_PERSP_CORRECT       1024
#define IDS_FORCE_LINEAR_FOG            1025
#define IDS_FORCE_SOFTWARE              1026
#define IDS_DISABLE_FILTER              1027
#define IDS_ENSURE_VS                   1028
#define IDS_USE_INDEX_BUFFERS           1029
#define IDS_DISABLE_DITHER              1030
#define IDS_ANTIALIAS                   1031
#define IDS_DISABLE_MIPMAP              1032
#define IDS_DISABLE_SPECULAR            1033
#define IDS_ENABLE_SCREEN_DUMP          1034
#define IDS_ENABLE_DEBUG_GFX            1035
#define IDS_VERTEX_CACHE                1036
#define IDS_TEXTURE_CACHE_MGMT          1037
#define IDS_SORT_TRANSPARENT            1038
#define IDS_TEXTURE_VIDEO_FORMAT        1039
#define IDS_SPRITE_VIDEO_FORMAT         1040
#define IDS_CHILD_WINDOW_RENDER         1041
#define IDS_BORDERLESS                  1042
#define IDS_CLIP_CURSOR                 1043
#define IDS_ALWAYS_HANDLE_INPUT         1044
#define IDS_POSITION_X                  1045
#define IDS_POSITION_Y                  1046
#define IDS_LANGUAGE                    1047
#define IDS_UI_LANGUAGE                 1048
#define IDS_LANG_GERMAN                 1049
#define IDS_LANG_ENGLISH                1050
#define IDS_LANG_SPANISH                1051
#define IDS_LANG_ITALIAN                1052
#define IDS_LANG_FRENCH                 1053
#define IDS_UI_ENGLISH                  1054
#define IDS_UI_CHINESE                  1055
#define IDS_SKIP_OPENING                1056
#define IDS_APPLY_HOTFIX                1057
#define IDS_UNLOCK_FRAMERATE            1058
#define IDS_UNLOCK_WIDESCREEN           1059
#define IDS_UNLOCK_HIGHRES              1060
#define IDS_DEBUG                       1061
#define IDS_ROOKIE                      1062
#define IDS_ERR_NO_CONFIG               1063
#define IDS_ERR_CANNOT_SAVE             1064
#define IDS_ERR_DIALOG_CREATE           1065
#define IDS_ERR_CONFIG_TITLE            1066
#define IDS_WARN_CONFIG_PATH            1067
#define IDS_WARN_CONFIG_TITLE           1068
#define IDS_SAVE_SUCCESS                1069
#define IDS_SAVE_TITLE                  1070

// String Table IDs for Chinese (2000-2999)
#define IDS_CN_DIALOG_TITLE             2000
#define IDS_CN_BTN_OK                   2001
#define IDS_CN_BTN_CANCEL               2002
#define IDS_CN_BTN_DEFAULTS             2003
#define IDS_CN_RESET_CONFIRM            2004
#define IDS_CN_RESET_TITLE              2005
#define IDS_CN_GROUP_STARTUP            2006
#define IDS_CN_GROUP_GRAPHICS           2007
#define IDS_CN_GROUP_WINDOW             2008
#define IDS_CN_GROUP_GAME               2009
#define IDS_CN_GROUP_INTERFACE          2010
#define IDS_CN_LOG_MODE                 2011
#define IDS_CN_LOG_APPEND               2012
#define IDS_CN_LOG_OVERWRITE            2013
#define IDS_CN_VERBOSE                  2014
#define IDS_CN_MANUAL_SETUP             2015
#define IDS_CN_LOAD_ALL_MGR             2016
#define IDS_CN_LOAD_ALL_BB              2017
#define IDS_CN_LOAD_ALL_PLUGINS         2018
#define IDS_CN_DRIVER_ID                2019
#define IDS_CN_BPP                      2020
#define IDS_CN_WIDTH                    2021
#define IDS_CN_HEIGHT                   2022
#define IDS_CN_FULLSCREEN               2023
#define IDS_CN_DISABLE_PERSP_CORRECT    2024
#define IDS_CN_FORCE_LINEAR_FOG         2025
#define IDS_CN_FORCE_SOFTWARE           2026
#define IDS_CN_DISABLE_FILTER           2027
#define IDS_CN_ENSURE_VS                2028
#define IDS_CN_USE_INDEX_BUFFERS        2029
#define IDS_CN_DISABLE_DITHER           2030
#define IDS_CN_ANTIALIAS                2031
#define IDS_CN_DISABLE_MIPMAP           2032
#define IDS_CN_DISABLE_SPECULAR         2033
#define IDS_CN_ENABLE_SCREEN_DUMP       2034
#define IDS_CN_ENABLE_DEBUG_GFX         2035
#define IDS_CN_VERTEX_CACHE             2036
#define IDS_CN_TEXTURE_CACHE_MGMT       2037
#define IDS_CN_SORT_TRANSPARENT         2038
#define IDS_CN_TEXTURE_VIDEO_FORMAT     2039
#define IDS_CN_SPRITE_VIDEO_FORMAT      2040
#define IDS_CN_CHILD_WINDOW_RENDER      2041
#define IDS_CN_BORDERLESS               2042
#define IDS_CN_CLIP_CURSOR              2043
#define IDS_CN_ALWAYS_HANDLE_INPUT      2044
#define IDS_CN_POSITION_X               2045
#define IDS_CN_POSITION_Y               2046
#define IDS_CN_LANGUAGE                 2047
#define IDS_CN_UI_LANGUAGE              2048
#define IDS_CN_LANG_GERMAN              2049
#define IDS_CN_LANG_ENGLISH             2050
#define IDS_CN_LANG_SPANISH             2051
#define IDS_CN_LANG_ITALIAN             2052
#define IDS_CN_LANG_FRENCH              2053
#define IDS_CN_UI_ENGLISH               2054
#define IDS_CN_UI_CHINESE               2055
#define IDS_CN_SKIP_OPENING             2056
#define IDS_CN_APPLY_HOTFIX             2057
#define IDS_CN_UNLOCK_FRAMERATE         2058
#define IDS_CN_UNLOCK_WIDESCREEN        2059
#define IDS_CN_UNLOCK_HIGHRES           2060
#define IDS_CN_DEBUG                    2061
#define IDS_CN_ROOKIE                   2062
#define IDS_CN_ERR_NO_CONFIG            2063
#define IDS_CN_ERR_CANNOT_SAVE          2064
#define IDS_CN_ERR_DIALOG_CREATE        2065
#define IDS_CN_ERR_CONFIG_TITLE         2066
#define IDS_CN_WARN_CONFIG_PATH         2067
#define IDS_CN_WARN_CONFIG_TITLE        2068
#define IDS_CN_SAVE_SUCCESS             2069
#define IDS_CN_SAVE_TITLE               2070

// Controls
#define IDC_BUTTON_DEFAULTS             1000
#define IDC_COMBO_LOGMODE               1001
#define IDC_CHECK_VERBOSE               1002
#define IDC_CHECK_MANUALSETUP           1003
#define IDC_CHECK_LOADALLMGR            1004
#define IDC_CHECK_LOADALLBB             1005
#define IDC_CHECK_LOADALLPLUG           1006

#define IDC_EDIT_DRIVER                 1101
#define IDC_COMBO_BPP                   1102
#define IDC_EDIT_WIDTH                  1103
#define IDC_EDIT_HEIGHT                 1104
#define IDC_CHECK_FULLSCREEN            1105
#define IDC_CHECK_DISPERSPCORRECT       1106
#define IDC_CHECK_FORCELINEARFOG        1107
#define IDC_CHECK_FORCESOFTWARE         1108
#define IDC_CHECK_DISABLEFILTER         1109
#define IDC_CHECK_ENSUREVS              1110
#define IDC_CHECK_USEINDEXBUFFERS       1111
#define IDC_CHECK_DISABLEDITHER         1112
#define IDC_EDIT_ANTIALIAS              1113
#define IDC_CHECK_DISABLEMIPMAP         1114
#define IDC_CHECK_DISABLESPECULAR       1115
#define IDC_CHECK_ENABLESCREENDUMP      1116
#define IDC_CHECK_ENABLEDEBUGMODE_GFX   1117
#define IDC_EDIT_VERTEXCACHE            1118
#define IDC_CHECK_TEXCACHEMGMT          1119
#define IDC_CHECK_SORTTRANSPARENT       1120
#define IDC_EDIT_TEXVIDFORMAT           1121
#define IDC_EDIT_SPRVIDFORMAT           1122

#define IDC_CHECK_CHILDWINRENDER        1201
#define IDC_CHECK_BORDERLESS            1202
#define IDC_CHECK_CLIPCURSOR            1203
#define IDC_CHECK_ALWAYSHANDLEINPUT     1204
#define IDC_EDIT_POSX                   1205
#define IDC_EDIT_POSY                   1206

#define IDC_COMBO_LANG                  1301
#define IDC_CHECK_SKIPOPENING           1302
#define IDC_CHECK_APPLYHOTFIX           1303
#define IDC_CHECK_UNLOCKFRAMERATE       1304
#define IDC_CHECK_UNLOCKWIDESCREEN      1305
#define IDC_CHECK_UNLOCKHIGHRES         1306
#define IDC_CHECK_DEBUG                 1307
#define IDC_CHECK_ROOKIE                1308

#define IDC_GROUP_STARTUP               1401
#define IDC_GROUP_GRAPHICS              1402
#define IDC_GROUP_WINDOW                1403
#define IDC_GROUP_GAME                  1404
#define IDC_GROUP_INTERFACE             1500
#define IDC_COMBO_LANGUAGE              1501

#endif // CONFIGTOOL_RESOURCE_H
