#ifndef PLAYER_CONFIG_H
#define PLAYER_CONFIG_H

#define PLAYER_VERSION_MAJOR 0
#define PLAYER_VERSION_MINOR 3
#define PLAYER_VERSION_PATCH 6
#define PLAYER_VERSION_TWEAK 0
#define PLAYER_VERSION "0.3.6.0"
#define PLAYER_DESCRIPTION "The brand-new player for Ballance"

#define PLAYER_DEFAULT_WIDTH 640
#define PLAYER_DEFAULT_HEIGHT 480
#define PLAYER_DEFAULT_BPP 32

#endif // PLAYER_CONFIG_H
