#define VS_VERSION_INFO                 1
#define IDS_MAIN_WND_NAME               102
#define IDS_RENDER_WND_NAME             103
#define IDS_MAIN_WND_CLASS_NAME         104
#define IDS_RENDER_WND_CLASS_NAME       105
#define IDI_PLAYER                      106
#define IDR_ACCEL                       128
#define IDM_APP_ABOUT                   129
#define IDM_APP_CONFIG                  133
#define IDD_FULLSCREEN_SETUP            130
#define IDD_ABOUT                       131
#define IDD_CONFIG                      132
#define IDC_LB_DRIVER                   1007
#define IDC_LB_SCREEN_MODE              1008

// Config dialog string table IDs, English (1000-1999)
#define IDS_DIALOG_TITLE                1000
#define IDS_BTN_OK                      1001
#define IDS_BTN_CANCEL                  1002
#define IDS_BTN_DEFAULTS                1003
#define IDS_RESET_CONFIRM               1004
#define IDS_RESET_TITLE                 1005
#define IDS_GROUP_STARTUP               1006
#define IDS_GROUP_GRAPHICS              1007
#define IDS_GROUP_WINDOW                1008
#define IDS_GROUP_GAME                  1009
#define IDS_GROUP_INTERFACE             1010
#define IDS_LOG_MODE                    1011
#define IDS_LOG_APPEND                  1012
#define IDS_LOG_OVERWRITE               1013
#define IDS_VERBOSE                     1014
#define IDS_MANUAL_SETUP                1015
#define IDS_DRIVER_ID                   1019
#define IDS_BPP                         1020
#define IDS_WIDTH                       1021
#define IDS_HEIGHT                      1022
#define IDS_FULLSCREEN                  1023
#define IDS_DISABLE_PERSP_CORRECT       1024
#define IDS_FORCE_LINEAR_FOG            1025
#define IDS_FORCE_SOFTWARE              1026
#define IDS_DISABLE_FILTER              1027
#define IDS_ENSURE_VS                   1028
#define IDS_USE_INDEX_BUFFERS           1029
#define IDS_DISABLE_DITHER              1030
#define IDS_ANTIALIAS                   1031
#define IDS_DISABLE_MIPMAP              1032
#define IDS_DISABLE_SPECULAR            1033
#define IDS_ENABLE_SCREEN_DUMP          1034
#define IDS_ENABLE_DEBUG_GFX            1035
#define IDS_VERTEX_CACHE                1036
#define IDS_TEXTURE_CACHE_MGMT          1037
#define IDS_SORT_TRANSPARENT            1038
#define IDS_TEXTURE_VIDEO_FORMAT        1039
#define IDS_SPRITE_VIDEO_FORMAT         1040
#define IDS_CHILD_WINDOW_RENDER         1041
#define IDS_BORDERLESS                  1042
#define IDS_CLIP_CURSOR                 1043
#define IDS_ALWAYS_HANDLE_INPUT         1044
#define IDS_POSITION_X                  1045
#define IDS_POSITION_Y                  1046
#define IDS_LANGUAGE                    1047
#define IDS_UI_LANGUAGE                 1048
#define IDS_LANG_GERMAN                 1049
#define IDS_LANG_ENGLISH                1050
#define IDS_LANG_SPANISH                1051
#define IDS_LANG_ITALIAN                1052
#define IDS_LANG_FRENCH                 1053
#define IDS_UI_ENGLISH                  1054
#define IDS_UI_CHINESE                  1055
#define IDS_SKIP_OPENING                1056
#define IDS_APPLY_HOTFIX                1057
#define IDS_UNLOCK_FRAMERATE            1058
#define IDS_UNLOCK_WIDESCREEN           1059
#define IDS_UNLOCK_HIGHRES              1060
#define IDS_DEBUG                       1061
#define IDS_ROOKIE                      1062
#define IDS_ERR_NO_CONFIG               1063
#define IDS_ERR_CANNOT_SAVE             1064
#define IDS_ERR_DIALOG_CREATE           1065
#define IDS_ERR_CONFIG_TITLE            1066
#define IDS_WARN_CONFIG_PATH            1067
#define IDS_WARN_CONFIG_TITLE           1068
#define IDS_RESTART_REQUIRED            1069
#define IDS_RESTART_REQUIRED_TITLE      1070

// Config dialog string table IDs, Chinese (2000-2999)
#define IDS_CN_DIALOG_TITLE             2000
#define IDS_CN_BTN_OK                   2001
#define IDS_CN_BTN_CANCEL               2002
#define IDS_CN_BTN_DEFAULTS             2003
#define IDS_CN_RESET_CONFIRM            2004
#define IDS_CN_RESET_TITLE              2005
#define IDS_CN_GROUP_STARTUP            2006
#define IDS_CN_GROUP_GRAPHICS           2007
#define IDS_CN_GROUP_WINDOW             2008
#define IDS_CN_GROUP_GAME               2009
#define IDS_CN_GROUP_INTERFACE          2010
#define IDS_CN_LOG_MODE                 2011
#define IDS_CN_LOG_APPEND               2012
#define IDS_CN_LOG_OVERWRITE            2013
#define IDS_CN_VERBOSE                  2014
#define IDS_CN_MANUAL_SETUP             2015
#define IDS_CN_DRIVER_ID                2019
#define IDS_CN_BPP                      2020
#define IDS_CN_WIDTH                    2021
#define IDS_CN_HEIGHT                   2022
#define IDS_CN_FULLSCREEN               2023
#define IDS_CN_DISABLE_PERSP_CORRECT    2024
#define IDS_CN_FORCE_LINEAR_FOG         2025
#define IDS_CN_FORCE_SOFTWARE           2026
#define IDS_CN_DISABLE_FILTER           2027
#define IDS_CN_ENSURE_VS                2028
#define IDS_CN_USE_INDEX_BUFFERS        2029
#define IDS_CN_DISABLE_DITHER           2030
#define IDS_CN_ANTIALIAS                2031
#define IDS_CN_DISABLE_MIPMAP           2032
#define IDS_CN_DISABLE_SPECULAR         2033
#define IDS_CN_ENABLE_SCREEN_DUMP       2034
#define IDS_CN_ENABLE_DEBUG_GFX         2035
#define IDS_CN_VERTEX_CACHE             2036
#define IDS_CN_TEXTURE_CACHE_MGMT       2037
#define IDS_CN_SORT_TRANSPARENT         2038
#define IDS_CN_TEXTURE_VIDEO_FORMAT     2039
#define IDS_CN_SPRITE_VIDEO_FORMAT      2040
#define IDS_CN_CHILD_WINDOW_RENDER      2041
#define IDS_CN_BORDERLESS               2042
#define IDS_CN_CLIP_CURSOR              2043
#define IDS_CN_ALWAYS_HANDLE_INPUT      2044
#define IDS_CN_POSITION_X               2045
#define IDS_CN_POSITION_Y               2046
#define IDS_CN_LANGUAGE                 2047
#define IDS_CN_UI_LANGUAGE              2048
#define IDS_CN_LANG_GERMAN              2049
#define IDS_CN_LANG_ENGLISH             2050
#define IDS_CN_LANG_SPANISH             2051
#define IDS_CN_LANG_ITALIAN             2052
#define IDS_CN_LANG_FRENCH              2053
#define IDS_CN_UI_ENGLISH               2054
#define IDS_CN_UI_CHINESE               2055
#define IDS_CN_SKIP_OPENING             2056
#define IDS_CN_APPLY_HOTFIX             2057
#define IDS_CN_UNLOCK_FRAMERATE         2058
#define IDS_CN_UNLOCK_WIDESCREEN        2059
#define IDS_CN_UNLOCK_HIGHRES           2060
#define IDS_CN_DEBUG                    2061
#define IDS_CN_ROOKIE                   2062
#define IDS_CN_ERR_NO_CONFIG            2063
#define IDS_CN_ERR_CANNOT_SAVE          2064
#define IDS_CN_ERR_DIALOG_CREATE        2065
#define IDS_CN_ERR_CONFIG_TITLE         2066
#define IDS_CN_WARN_CONFIG_PATH         2067
#define IDS_CN_WARN_CONFIG_TITLE        2068
#define IDS_CN_RESTART_REQUIRED         2069
#define IDS_CN_RESTART_REQUIRED_TITLE   2070

// Config dialog controls
#define IDC_BUTTON_DEFAULTS             2000
#define IDC_COMBO_LOGMODE               2001
#define IDC_CHECK_VERBOSE               2002
#define IDC_CHECK_MANUALSETUP           2003

#define IDC_CONFIG_EDIT_DRIVER          2101
#define IDC_COMBO_BPP                   2102
#define IDC_EDIT_WIDTH                  2103
#define IDC_EDIT_HEIGHT                 2104
#define IDC_CHECK_FULLSCREEN            2105
#define IDC_CHECK_DISPERSPCORRECT       2106
#define IDC_CHECK_FORCELINEARFOG        2107
#define IDC_CHECK_FORCESOFTWARE         2108
#define IDC_CHECK_DISABLEFILTER         2109
#define IDC_CHECK_ENSUREVS              2110
#define IDC_CHECK_USEINDEXBUFFERS       2111
#define IDC_CHECK_DISABLEDITHER         2112
#define IDC_EDIT_ANTIALIAS              2113
#define IDC_CHECK_DISABLEMIPMAP         2114
#define IDC_CHECK_DISABLESPECULAR       2115
#define IDC_CHECK_ENABLESCREENDUMP      2116
#define IDC_CHECK_ENABLEDEBUGMODE_GFX   2117
#define IDC_EDIT_VERTEXCACHE            2118
#define IDC_CHECK_TEXCACHEMGMT          2119
#define IDC_CHECK_SORTTRANSPARENT       2120
#define IDC_EDIT_TEXVIDFORMAT           2121
#define IDC_EDIT_SPRVIDFORMAT           2122

#define IDC_CHECK_CHILDWINRENDER        2201
#define IDC_CHECK_BORDERLESS            2202
#define IDC_CHECK_CLIPCURSOR            2203
#define IDC_CHECK_ALWAYSHANDLEINPUT     2204
#define IDC_EDIT_POSX                   2205
#define IDC_EDIT_POSY                   2206

#define IDC_COMBO_LANG                  2301
#define IDC_CHECK_SKIPOPENING           2302
#define IDC_CHECK_APPLYHOTFIX           2303
#define IDC_CHECK_UNLOCKFRAMERATE       2304
#define IDC_CHECK_UNLOCKWIDESCREEN      2305
#define IDC_CHECK_UNLOCKHIGHRES         2306
#define IDC_CHECK_DEBUG                 2307
#define IDC_CHECK_ROOKIE                2308

#define IDC_GROUP_STARTUP               2401
#define IDC_GROUP_GRAPHICS              2402
#define IDC_GROUP_WINDOW                2403
#define IDC_GROUP_GAME                  2404
#define IDC_GROUP_INTERFACE             2500
#define IDC_COMBO_LANGUAGE              2501

// Config dialog controls mapped by CGameConfig member name.
#define IDC_CONFIG_logMode              IDC_COMBO_LOGMODE
#define IDC_CONFIG_verbose              IDC_CHECK_VERBOSE
#define IDC_CONFIG_manualSetup          IDC_CHECK_MANUALSETUP
#define IDC_CONFIG_driver               IDC_CONFIG_EDIT_DRIVER
#define IDC_CONFIG_bpp                  IDC_COMBO_BPP
#define IDC_CONFIG_width                IDC_EDIT_WIDTH
#define IDC_CONFIG_height               IDC_EDIT_HEIGHT
#define IDC_CONFIG_antialias            IDC_EDIT_ANTIALIAS
#define IDC_CONFIG_vertexCache          IDC_EDIT_VERTEXCACHE
#define IDC_CONFIG_posX                 IDC_EDIT_POSX
#define IDC_CONFIG_posY                 IDC_EDIT_POSY
#define IDC_CONFIG_langId               IDC_COMBO_LANG
#define IDC_CONFIG_fullscreen           IDC_CHECK_FULLSCREEN
#define IDC_CONFIG_disablePerspectiveCorrection IDC_CHECK_DISPERSPCORRECT
#define IDC_CONFIG_forceLinearFog       IDC_CHECK_FORCELINEARFOG
#define IDC_CONFIG_forceSoftware        IDC_CHECK_FORCESOFTWARE
#define IDC_CONFIG_disableFilter        IDC_CHECK_DISABLEFILTER
#define IDC_CONFIG_ensureVertexShader   IDC_CHECK_ENSUREVS
#define IDC_CONFIG_useIndexBuffers      IDC_CHECK_USEINDEXBUFFERS
#define IDC_CONFIG_disableDithering     IDC_CHECK_DISABLEDITHER
#define IDC_CONFIG_disableMipmap        IDC_CHECK_DISABLEMIPMAP
#define IDC_CONFIG_disableSpecular      IDC_CHECK_DISABLESPECULAR
#define IDC_CONFIG_enableScreenDump     IDC_CHECK_ENABLESCREENDUMP
#define IDC_CONFIG_enableDebugMode      IDC_CHECK_ENABLEDEBUGMODE_GFX
#define IDC_CONFIG_textureCacheManagement IDC_CHECK_TEXCACHEMGMT
#define IDC_CONFIG_sortTransparentObjects IDC_CHECK_SORTTRANSPARENT
#define IDC_CONFIG_childWindowRendering IDC_CHECK_CHILDWINRENDER
#define IDC_CONFIG_borderless           IDC_CHECK_BORDERLESS
#define IDC_CONFIG_clipCursor           IDC_CHECK_CLIPCURSOR
#define IDC_CONFIG_alwaysHandleInput    IDC_CHECK_ALWAYSHANDLEINPUT
#define IDC_CONFIG_skipOpening          IDC_CHECK_SKIPOPENING
#define IDC_CONFIG_applyHotfix          IDC_CHECK_APPLYHOTFIX
#define IDC_CONFIG_unlockFramerate      IDC_CHECK_UNLOCKFRAMERATE
#define IDC_CONFIG_unlockWidescreen     IDC_CHECK_UNLOCKWIDESCREEN
#define IDC_CONFIG_unlockHighResolution IDC_CHECK_UNLOCKHIGHRES
#define IDC_CONFIG_debug                IDC_CHECK_DEBUG
#define IDC_CONFIG_rookie               IDC_CHECK_ROOKIE
#define IDC_CONFIG_textureVideoFormat   IDC_EDIT_TEXVIDFORMAT
#define IDC_CONFIG_spriteVideoFormat    IDC_EDIT_SPRVIDFORMAT
